version: '3.8'

services:
  sync-bucket:
    image: ghcr.io/mbap-dev/sync-bucket:latest
    container_name: minio-s3-synchronizer
    environment:
      # Configurações do MinIO
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
      # Configurações do Amazon S3
      - S3_ENDPOINT=https://s3.us-west-2.amazonaws.com
      - S3_ACCESS_KEY=aws_access_key
      - S3_SECRET_KEY=aws_secret_key
      # Configuração dos buckets (origem:destino)
      - BUCKET_PAIRS=bucket1:dest1,bucket2:dest2,bucket3:backup
      # Agendamento Cron (padrão: diário às 2h)
      - CRON_SCHEDULE=0 2 * * *
      # Configurações adicionais
      - TZ=America/Sao_Paulo
      - LOG_LEVEL=info                   # debug/info/warn/error

    volumes:
      - sync-logs:/var/log
      - /etc/localtime:/etc/localtime:ro

    networks:
      - sync-network

    restart: unless-stopped

volumes:
  sync-logs:
    driver: local

networks:
  sync-network:
    driver: bridge
