version: '3.8'

services:
  swarm-cronjob:
    image: crazymax/swarm-cronjob:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

  minio-s3-sync:
    image: ghcr.io/mbap-dev/sync-buckets:latest
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=seu_minio_access_key
      - MINIO_SECRET_KEY=seu_minio_secret_key
      - S3_ENDPOINT=https://s3.sa-east-1.amazonaws.com
      - S3_ACCESS_KEY=seu_aws_access_key
      - S3_SECRET_KEY=seu_aws_secret_key
      - BUCKET_PAIRS=bucket1:dest1,bucket2:dest2
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure
        max_attempts: 1
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=CRON_TZ=America/Sao_Paulo 0 2 * * *
        - swarm.cronjob.replicas=1
        - swarm.cronjob.skip-running=true
        - swarm.cronjob.startingDeadlineSeconds=60


networks:
  app_network:
    external: true
