version: '3.8'

services:
  # Serviço do swarm-cronjob
  swarm-cronjob:
    image: crazymax/swarm-cronjob:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

  # Serviço de sincronização MinIO -> S3
  minio-s3-sync:
    image: ghcr.io/mbap-dev/sync-buckets:latest
    environment:
      # Configurações do MinIO
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=seu_minio_access_key
      - MINIO_SECRET_KEY=seu_minio_secret_key

      # Configurações do Amazon S3
      - S3_ENDPOINT=https://s3.sa-east-1.amazonaws.com
      - S3_ACCESS_KEY=seu_aws_access_key
      - S3_SECRET_KEY=seu_aws_secret_key

      # Buckets para sincronizar (origem:destino)
      - BUCKET_PAIRS=bucket1:dest1,bucket2:dest2,bucket3:backup3

    deploy:
      replicas: 0  # Não roda por padrão
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=CRON_TZ=America/Sao_Paulo 0 2 * * *  # Diário às 2h
        - swarm.cronjob.replicas=1
        - swarm.cronjob.skip-running=true  # Evita execuções sobrepostas

networks:
  default:
    external: true
    name: minio_network  # Ajuste conforme sua rede
